spring.application.name=chat-backend
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-plain-cell-azl25lsy.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Zbozwdg46LUe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG


jwt.secret=change-this-to-a-long-random-secret-key-at-least-32-chars
jwt.expiration=86400000
